// <auto-generated />
using IbankLogin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IbankLogin.Migrations
{
    [DbContext(typeof(IbankLoginContext))]
    [Migration("20200428062736_SeedInitialData")]
    partial class SeedInitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IbankLogin.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Agencia");

                    b.Property<int>("Conta");

                    b.Property<string>("Nome");

                    b.Property<int>("Senha");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");

                    b.HasData(
                        new { ClienteId = 1, Agencia = 1234, Conta = 987654, Nome = "Antonio", Senha = 1122 },
                        new { ClienteId = 2, Agencia = 1234, Conta = 456789, Nome = "Maria", Senha = 2233 },
                        new { ClienteId = 3, Agencia = 1234, Conta = 111145, Nome = "Ana", Senha = 4875 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
